### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by LEQADA** [sphereio/sphere-stock-export#10]
"socket hang up" error occurs on 

    stock-export --sphereHost api.sphere.io --projectKey "carharrt-demo-83" --queryString "supplyChannel(not id=\"20c23c73-8db8-4c1a-8a57-17f95ae70a71\" and not id=\"50615f7e-6412-456e-9b92-9aeef07df63a\")" --targetDir "test-data"

I think that there must be some repeater when API fails.

![image](https://cloud.githubusercontent.com/assets/9251453/20484902/b4f4a8e4-aff9-11e6-8e55-15f32a31f44f.png)

**Comment by LEQADA** [comment]
Will be fixed by this pull request
https://github.com/sphereio/sphere-node-sdk/pull/190

**Comment by butenkor** [comment]
@LEQADA please do not close as long as it is not merged and released.

**Comment by LEQADA** [comment]
Fixed by this pull request (merged)
https://github.com/sphereio/sphere-node-sdk/pull/190

**Comment by butenkor** [comment]
@LEQADA I think it is not fixed until it is not released with newest SDK version (1.17.0): https://github.com/sphereio/sphere-stock-export/blob/master/package.json#L42

**Comment by junajan** [comment]
Merged and released here https://github.com/sphereio/sphere-node-sdk/releases/tag/v1.17.0 - thus we can finally close this issue .. @LEQADA now it's your time :-)

**Comment by LEQADA** [comment]
@junajan I think Roman meant that SDK version should be updated from 1.7.0 to at least 1.17.0 to make this issue fixed.

**Comment by LEQADA** [comment]
Here https://github.com/sphereio/sphere-stock-export/blob/master/package.json#L42
